services:
  postgres:
    container_name: postgres
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: sportscentre
    volumes:
      - data-postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - spring

  configurationboapi:
    container_name: configurationboapi
    image: pablo7molina/configurationboapi:latest
    ports:
      - "8002:8002"
    env_file: backoffice/ConfigurationBOApi/.env
    networks:
      - spring
    restart: always

  bookingsservice:
    container_name: bookingsservice
    image: pablo7molina/bookingsservice:latest
    ports:
      - "8001:8001"
    env_file: services/BookingsService/.env
    networks:
      - spring
    depends_on:
      - postgres
    restart: always

volumes:
  data-postgres:

networks:
  spring:
